### ISSUE TITLE
Extend environment key:value pattern to allow reading from Drone secret 

### ISSUE THREAD

**Issue by jayminkapish** [oliver006/drone-cloud-run#2]
Drone 1.0 (don't know if previous Drone versions supported this) allows to read and set value of an environment variable through Drone setting, for example: 

```
environment:
        DB_PASSWORD:
          from_secret: STG_DB_PASSWORD
```

It would be great to extend `environment` parsing logic to accept this pattern.

I got the following errors from Drone

```

2021/01/05 20:37:43 json.Unmarshal() err: json: cannot unmarshal number into Go value of type string
--
6 | 2021/01/05 20:37:43 os.Getenv(PLUGIN_ENVIRONMENT):

```

```
Deployment failed
--
32 | ERROR: (gcloud.beta.run.deploy) INVALID_ARGUMENT: Invalid JSON payload received. Unknown name "initializers" at 'service.metadata': Cannot find field.
33 | Invalid JSON payload received. Unknown name "initializers" at 'service.spec.run_latest.configuration.revision_template.metadata': Cannot find field.
34 | - '@type': type.googleapis.com/google.rpc.BadRequest
35 | fieldViolations:
36 | - description: "Invalid JSON payload received. Unknown name \"initializers\" at\
37 | \ 'service.metadata': Cannot find field."
38 | field: service.metadata
39 | - description: "Invalid JSON payload received. Unknown name \"initializers\" at\
40 | \ 'service.spec.run_latest.configuration.revision_template.metadata': Cannot\
41 | \ find field."
42 | field: service.spec.run_latest.configuration.revision_template.metadata
43 | 2021/01/05 20:37:44 runConfig() err: error: exit status 1

```

**Comment by adityanatraj** [comment]
something critical to think about: this would leak drone secrets to the google cloud console where they'll be exposed in the configuration YAML

**Comment by jayminkapish** [comment]
That's a very good point and it's true for any other `environment` variable passed through key:value as well as per example in readme.

**Comment by adityanatraj** [comment]
@oliver006 do you have thoughts on this? 

personally, i'm discomforted by my above note. 

that said, i wonder if a separate feature "the ability to reference env vars in the drone build environment in the `environment` section of the cloud run configuration" would be a) useful and b) provide this feature without feeling guilty about it being about secrets and dealing with them responsibly...

**Comment by jayminkapish** [comment]
Thanks for thinking about this more broadly.

More on this env pattern from Drone docs: https://docs.drone.io/pipeline/environment/syntax/#from-secrets

**Comment by oliver006** [comment]
I think I'd want to differentiate between secrets you need to run the plugin and secrets that are passed to the Cloud Run container.

Secrets needed for running the plugin you should be able to pass via `from_secret`, right? 

Secrets for the container are probably better kept in something like Vault instead of being passed via Drone. They can also be easily looked up in the Cloud Run console so the level of "secrectness" is questionable value (I think that's what Aditya is referring to in his comment?)

That said, see this part of the code here: https://github.com/oliver006/drone-cloud-run/blob/master/main.go#L91-L98
I guess it could be documented better in the README but you can pass a config item to the plugin named e.g. `env_secret_api_key` which can utilize `from_secret`. It will trim the `env_secret_` prefix and inject the variable name (in this case `api_key`) into the env of the container.

**Comment by jayminkapish** [comment]
Thanks again both for your help brainstorm this. FYI, we've switched to secret manager and no longer need this feature.

**Comment by oliver006** [comment]
👍
